### PR TITLE
Try ~/.config/gotify/cli.json config location

### PR DESCRIPTION
**Pull request by paper42**

### CODE REVIEW

**Comment by jmattheis** [comment]
Hey @paper42, sorry that I missed this PR :|. 
Does the `$XDG_CONFIG_HOME/gotify/cli.json` not work for you because this should basically evaluate to the added path, if you haven't overridden `XDG_CONFIG_HOME`.

**Comment by paper42** [comment]
Hi, `XDG_CONFIG_HOME` isn't always set in minimal setups, for example on a server.

**Comment by jmattheis** [comment]
When it isn't set, then it falls back to `$HOME`, or am I wrong?

**Comment by paper42** [comment]
yes, it does, but it falls back to `~/.gotify/cli.json`, while I would expect (and most projects do it) it should fall back to `~/.config/gotify/cli.json`. Basically when `$XDG_CONFIG_HOME` is not set, we should act like `XDG_CONFIG_HOME=~/.config/`

**Comment by jmattheis** [comment]
Are you sure? Tested with current master.
```
$ echo $XDG_CONFIG_HOME

$ echo $HOME
/home/jm
$ go run . config
Used Config: /home/jm/.config/gotify/cli.json
URL: http://localhost:8080
Default Priority: 10
Token: Axxxxxxxxxx
```

**Pull request closed without merging**
