### PR TITLE
fix panic when no config and no priority argument

### LINKED ISSUE #50: Got golang panic when pushing message with --token parameter
I'd like to use gotify-cli in some automatic scripts invoked by some other services. When I tried to make a parameter settings like these and without the cli.json:
`gotify-cli push --url http://gotify.xxxxxxxx.com --token someToken messages`
I got a golang panic both on Linux and Windows:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xd8ea02]

goroutine 1 [running]:
github.com/gotify/cli/v2/command.doPush(0xc00079e2c0)
        /home/jm/src/gotify/cli/command/push.go:72 +0x342
gopkg.in/urfave/cli%2ev1.HandleAction({0xdc0020, 0xe66ce0}, 0x4)
        /home/jm/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:492 +0x7b
gopkg.in/urfave/cli%2ev1.Command.Run({{0xe3fecd, 0x4}, {0x0, 0x0}, {0xc0003f06e0, 0x1, 0x1}, {0xe4573b, 0x10}, {0x0, ...}, ...}, ...)
        /home/jm/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x8f8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00040f1e0, {0xc0000d8000, 0x7, 0x8})
        /home/jm/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x6ac
main.main()
        /home/jm/src/gotify/cli/cli.go:34 +0xf88
```
But if I run `gotify-cli init` or create a cli.json file with same url and token, it works well.

### PR DESCRIPTION
**Pull request by tessus**
fixes #50

### CODE REVIEW

**Comment by jmattheis** [comment]
Thanks

**Comment by tessus** [comment]
In issue #50 it was stated

> But the priority has been claimed that it has a default value with 0.

But after your change it leaves `priority` undefined. There is no else branch. I checked the rest of the code, but `priority` is nowhere to be set to `0`.

**Comment by jmattheis** [comment]
There is no "undefined" in Go, priority is an `int` meaning it cannot be undefined/nil it always has a value. It this case `0` is returned by the cli library, when a value is unset.

**Comment by tessus** [comment]
Well, if I test the code like so:

- without a cli.json (renamed it)
- `./build/gotify-cli-darwin-amd64 push --url https://bla.com/gotify --token Axxxxxxx "Test message".

The message is pushed to the clients, but there is no notification. If I add `-p X`, there is a notification. There are no errors in the server logs. I really think you should have left the else branch.

But maybe there is no notifiction for prio 0 messages, but I did that in my tests for the PR and I got a notification for prio 0 messages.

**Comment by tessus** [comment]
@jmattheis 

Since I wasn't able to find any documentation on this...

What is the highest priority and the lowest priority? Is `10` the highest or the lowest?
Also, the priority is not shown in the client (web ui or Android), so why is there a priority? Unfortunately the [docs](https://gotify.net/docs/) do not explain priorities at all.

Can you please shed some light on this?

**Comment by jmattheis** [comment]
> There are no errors in the server logs. I really think you should have left the else branch.

You probably had a default priority configured. This higher priority then caused the notification.

---

The webui colors the left border depending on the priority. gotify/android priorities are defined here https://github.com/gotify/android#message-priorities

Highest priority is int max and lowest int min.

**Comment by tessus** [comment]
Awesome, thanks. Any chance this info can be referenced in the docs?

**Comment by jmattheis** [comment]
Yeah, it could probably included in the pushmessage page.

**Pull request merged**
