### PR TITLE
Evaluate backslash n in message content

### PR DESCRIPTION
**Pull request by jmattheis**
See #17

### CODE REVIEW

**Comment by eternal-flame-AD** [comment]
Why do you use regex instead of a direct `strings.ReplaceAll`?

**Comment by jmattheis** [comment]
Well, pretty much because of habit. In java string.replaceAll is implemented via regex and the regex will be compiled on each call. But since this isn't Java I changed it to strings.ReplaceAll.

**Comment by eternal-flame-AD** [comment]
I think if we are going for escape strings, we should go for complete support rather than only substituting "\n" with a real newline character. At least we should be able to support double backslashes.

**Comment by jmattheis** [comment]
I don't really like the current solution, maybe you have a better one?

**Comment by eternal-flame-AD** [comment]
```golang
func Evaluate(s string) string {
	res := bytes.NewBuffer([]byte{})
	sourceReader := bytes.NewBufferString(s)
	for {
		r, _, err := sourceReader.ReadRune()
		if err == io.EOF {
			break
		}
		if r == '\\' {
			nextRune, _, err := sourceReader.ReadRune()
			if err == nil {
				switch nextRune {
				case '\\':
				case 't':
					r = '\t'
				case 'n':
					r = '\n'
				default:
					sourceReader.UnreadRune()
				}
			}
		}
		res.WriteRune(r)
	}
	return res.String()
}
```

How about this one? It passes your tests

**Pull request merged**
